# The Link: https://www.kaggle.com/datasets/sadmadlad/imdb-user-reviews

# Import Libraries and Datasets

In [3]:
import pandas as pd, numpy as np
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize

!pip install nltk
nltk.download('punkt_tab')
nltk.download('punkt')

pd.set_option('display.max_columns', None)

Requirement already satisfied: nltk in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.0)
Requirement already satisfied: colorama in c:\users\alireza hr\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package punkt_tab to C:\Users\Alireza
[nltk_data]     HR\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt to C:\Users\Alireza
[nltk_data]     HR\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [4]:
avengers = pd.read_csv("Raw Datasets\Avengers Endgame\movieReviews.csv")
Forrest_Gump = pd.read_csv('Raw Datasets\Forrest Gump\movieReviews.csv')
John_Wick = pd.read_csv("Raw Datasets\John Wick Chapter 3  Parabellum\movieReviews.csv")
Joker = pd.read_csv("Raw Datasets\Joker\movieReviews.csv")
Morbis = pd.read_csv("Raw Datasets\Morbius\movieReviews.csv")
Pulp_Fiction = pd.read_csv("Raw Datasets\Pulp Fiction\movieReviews.csv")
SpiderMan = pd.read_csv("Raw Datasets\SpiderMan No Way Home\movieReviews.csv")
The_Avengers = pd.read_csv("Raw Datasets\The Avengers\movieReviews.csv")
The_dark_night = pd.read_csv("Raw Datasets\The Dark Knight\movieReviews.csv")
Thor_Ragnarok = pd.read_csv("Raw Datasets\Thor Ragnarok\movieReviews.csv")

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:2: SyntaxWarning: invalid escape sequence '\F'
<>:3: SyntaxWarning: invalid escape sequence '\J'
<>:4: SyntaxWarning: invalid escape sequence '\J'
<>:5: SyntaxWarning: invalid escape sequence '\M'
<>:6: SyntaxWarning: invalid escape sequence '\P'
<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\T'
<>:9: SyntaxWarning: invalid escape sequence '\T'
<>:10: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:2: SyntaxWarning: invalid escape sequence '\F'
<>:3: SyntaxWarning: invalid escape sequence '\J'
<>:4: SyntaxWarning: invalid escape sequence '\J'
<>:5: SyntaxWarning: invalid escape sequence '\M'
<>:6: SyntaxWarning: invalid escape sequence '\P'
<>:7: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\T'
<>:9: SyntaxWarning: invalid escape sequence '\T'
<>:10: SyntaxWarning: invalid escape sequence '\T'
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:1: SyntaxWarning: invalid escape sequence '\A'
  avengers = pd.read_csv("Raw Datasets\Avengers Endgame\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:2: SyntaxWarning: invalid escape sequence '\F'
  Forrest_Gump = pd.read_csv('Raw Datasets\Forrest Gump\movieReviews.csv')
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:3: SyntaxWarning: invalid escape sequence '\J'
  John_Wick = pd.read_csv("Raw Datasets\John Wick Chapter 3  Parabellum\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:4: SyntaxWarning: invalid escape sequence '\J'
  Joker = pd.read_csv("Raw Datasets\Joker\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:5: SyntaxWarning: invalid escape sequence '\M'
  Morbis = pd.read_csv("Raw Datasets\Morbius\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:6: SyntaxWarning: invalid escape sequence '\P'
  Pulp_Fiction = pd.read_csv("Raw Datasets\Pulp Fiction\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:7: SyntaxWarning: invalid escape sequence '\S'
  SpiderMan = pd.read_csv("Raw Datasets\SpiderMan No Way Home\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:8: SyntaxWarning: invalid escape sequence '\T'
  The_Avengers = pd.read_csv("Raw Datasets\The Avengers\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:9: SyntaxWarning: invalid escape sequence '\T'
  The_dark_night = pd.read_csv("Raw Datasets\The Dark Knight\movieReviews.csv")
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\939608265.py:10: SyntaxWarning: invalid escape sequence '\T'
  Thor_Ragnarok = pd.read_csv("Raw Datasets\Thor Ragnarok\movieReviews.csv")

# Data Preprocessing

## Create movieID for each movie

In [5]:
ID = [1] * avengers.shape[0]
avengers['MovieID'] = ID

ID = [2] * Forrest_Gump.shape[0]
Forrest_Gump['MovieID'] = ID

ID = [3] * John_Wick.shape[0]
John_Wick['MovieID'] = ID

ID = [4] * Joker.shape[0]
Joker['MovieID'] = ID

ID = [5] * Morbis.shape[0]
Morbis['MovieID'] = ID

ID = [6] * Pulp_Fiction.shape[0]
Pulp_Fiction['MovieID'] = ID

ID = [7] * SpiderMan.shape[0]
SpiderMan['MovieID'] = ID

ID = [8] * The_Avengers.shape[0]
The_Avengers['MovieID'] = ID

ID = [9] * The_dark_night.shape[0]
The_dark_night['MovieID'] = ID

ID = [10] * Thor_Ragnarok.shape[0]
Thor_Ragnarok['MovieID'] = ID

## Combining datasets

In [6]:
dfs = [avengers, Forrest_Gump, John_Wick, Joker, Morbis, Pulp_Fiction, SpiderMan, The_Avengers, The_dark_night, Thor_Ragnarok]
dataset = pd.concat(dfs, ignore_index=True)

dataset.drop_duplicates()
dataset.reset_index()
# dataset.drop('index', axis=0, inplace=True)
dataset

,Date of Review,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review Title,Review,MovieID
0,4 May 2019,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",I've just come from watching Endgame and I mus...,1
1,6 May 2019,jtindahouse,75,127,4,Time travel is such a lazy way to write stories,Only a month or so back I was talking to a fri...,1
2,13 May 2019,arclinecreative,100,170,3,Overrated and full of filler,Continuity? 350M budget and no one looking ove...,1
3,3 August 2019,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",Maybe I would have enjoyed this more if I were...,1
4,13 December 2021,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie,Rating: 8.6Not as good as Infinity war pacing-...,1
...,...,...,...,...,...,...,...,...
47058,8 May 2018,pawelkazimierczyk,0,0,9,It's a very good film.,In this movie is a lot of funny moments and ac...,10
47059,14 September 2018,arno_caron,0,1,6,Too much,When Thor becomes Benny Hill. The sens of humo...,10
47060,23 May 2018,tobiaschabert,0,0,2,Disney makes this movie ridiculous,I mean why do you have to ruin every scene wit...,10
47061,11 July 2018,erl-91188,0,1,6,WATCH MORE TAIKA,If your takeaway from this movie is that super...,10
47062,18 November 2018,sguerdner,0,1,6,Hail to the war,"So, we've seen this movie with my sister a whi...",10

## Creating ID's for each reviewer

In [7]:
dataset['user_id'] = pd.factorize(dataset['User'])[0] + 1
dataset

,Date of Review,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review Title,Review,MovieID,user_id
0,4 May 2019,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",I've just come from watching Endgame and I mus...,1,1
1,6 May 2019,jtindahouse,75,127,4,Time travel is such a lazy way to write stories,Only a month or so back I was talking to a fri...,1,2
2,13 May 2019,arclinecreative,100,170,3,Overrated and full of filler,Continuity? 350M budget and no one looking ove...,1,3
3,3 August 2019,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",Maybe I would have enjoyed this more if I were...,1,4
4,13 December 2021,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie,Rating: 8.6Not as good as Infinity war pacing-...,1,5
...,...,...,...,...,...,...,...,...,...
47058,8 May 2018,pawelkazimierczyk,0,0,9,It's a very good film.,In this movie is a lot of funny moments and ac...,10,40912
47059,14 September 2018,arno_caron,0,1,6,Too much,When Thor becomes Benny Hill. The sens of humo...,10,40913
47060,23 May 2018,tobiaschabert,0,0,2,Disney makes this movie ridiculous,I mean why do you have to ruin every scene wit...,10,40914
47061,11 July 2018,erl-91188,0,1,6,WATCH MORE TAIKA,If your takeaway from this movie is that super...,10,40915
47062,18 November 2018,sguerdner,0,1,6,Hail to the war,"So, we've seen this movie with my sister a whi...",10,40916

- The reason for differences between the number of rows and the number of ID's is that some users left comments more than once

In [8]:
duplicates = dataset[dataset.duplicated(subset='User')]
duplicates

,Date of Review,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review Title,Review,MovieID,user_id
9,30 July 2019,dussaultjulien,115,210,1,Why?,I hate how people are saying that this movie i...,1,9
138,27 April 2019,marcusnichols,78,139,10,Really Marvel??? Poor Poor Movie To End On!!,I don't know where to start!!\nPlot holes all ...,1,134
160,30 April 2019,punitprakash,51,88,5,Disappointing and Unsatisfying,Infinity War is a Masterpiece and there is no ...,1,128
205,1 May 2019,ahamdshawaf,77,136,1,The scene,"The drama was not as it should be, the Comedy ...",1,183
299,2 May 2019,stomes85,91,160,1,Taco Tuesday librarian Hulk?,If you're a big Hulk fan don't waste your time...,1,267
...,...,...,...,...,...,...,...,...,...
46903,24 November 2017,anishsidi,1,6,9,Go and watch it.,One the best movie of MCU. Thor franchise has ...,10,7395
46907,13 July 2022,TrueCriticism,0,0,\n Was this review ...,A breathe of fresh air after two not-so-good T...,7.8(mild spoilers ahead)Thor: Ragnarok is supp...,10,6919
46955,2 December 2018,thanosroussis,0,1,6,Too many jokes,It is a pretty good movie the main problem for...,10,5433
46980,3 November 2017,enuen,0,4,8,Better than the first and second,While the predecessor was just plain horrible ...,10,7725
46982,3 November 2017,daisimalone,0,6,8,Embrace the silliness,"This is a great movie, but you have to be prep...",10,7726

## Cleaning Date Feature

In [9]:
dataset[['Day', 'Month', 'Year']] = dataset['Date of Review'].str.split(' ', expand=True)
dataset = dataset.drop('Date of Review', axis=1)
dataset

,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review Title,Review,MovieID,user_id,Day,Month,Year
0,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",I've just come from watching Endgame and I mus...,1,1,4,May,2019
1,jtindahouse,75,127,4,Time travel is such a lazy way to write stories,Only a month or so back I was talking to a fri...,1,2,6,May,2019
2,arclinecreative,100,170,3,Overrated and full of filler,Continuity? 350M budget and no one looking ove...,1,3,13,May,2019
3,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",Maybe I would have enjoyed this more if I were...,1,4,3,August,2019
4,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie,Rating: 8.6Not as good as Infinity war pacing-...,1,5,13,December,2021
...,...,...,...,...,...,...,...,...,...,...,...
47058,pawelkazimierczyk,0,0,9,It's a very good film.,In this movie is a lot of funny moments and ac...,10,40912,8,May,2018
47059,arno_caron,0,1,6,Too much,When Thor becomes Benny Hill. The sens of humo...,10,40913,14,September,2018
47060,tobiaschabert,0,0,2,Disney makes this movie ridiculous,I mean why do you have to ruin every scene wit...,10,40914,23,May,2018
47061,erl-91188,0,1,6,WATCH MORE TAIKA,If your takeaway from this movie is that super...,10,40915,11,July,2018
47062,sguerdner,0,1,6,Hail to the war,"So, we've seen this movie with my sister a whi...",10,40916,18,November,2018

## Combining Reviews

In [10]:
dataset['Review'] = dataset['Review Title'] + ".\n" + dataset['Review']

dataset.drop(columns=['Review Title'], inplace=True)
dataset

,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review,MovieID,user_id,Day,Month,Year
0,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",1,1,4,May,2019
1,jtindahouse,75,127,4,Time travel is such a lazy way to write storie...,1,2,6,May,2019
2,arclinecreative,100,170,3,Overrated and full of filler.\nContinuity? 350...,1,3,13,May,2019
3,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",1,4,3,August,2019
4,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie....,1,5,13,December,2021
...,...,...,...,...,...,...,...,...,...,...
47058,pawelkazimierczyk,0,0,9,It's a very good film..\nIn this movie is a lo...,10,40912,8,May,2018
47059,arno_caron,0,1,6,Too much.\nWhen Thor becomes Benny Hill. The s...,10,40913,14,September,2018
47060,tobiaschabert,0,0,2,Disney makes this movie ridiculous.\nI mean wh...,10,40914,23,May,2018
47061,erl-91188,0,1,6,WATCH MORE TAIKA.\nIf your takeaway from this ...,10,40915,11,July,2018
47062,sguerdner,0,1,6,"Hail to the war.\nSo, we've seen this movie wi...",10,40916,18,November,2018

## Calculating the number of Tokens for each review

In [11]:
def count_tokens(review):
    if isinstance(review, str):
        tokens = word_tokenize(review)
        return len(tokens)
    else:
        return 0

dataset['TokenCount'] = dataset['Review'].apply(count_tokens)
dataset

,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review,MovieID,user_id,Day,Month,Year,TokenCount
0,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",1,1,4,May,2019,1965
1,jtindahouse,75,127,4,Time travel is such a lazy way to write storie...,1,2,6,May,2019,361
2,arclinecreative,100,170,3,Overrated and full of filler.\nContinuity? 350...,1,3,13,May,2019,147
3,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",1,4,3,August,2019,995
4,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie....,1,5,13,December,2021,81
...,...,...,...,...,...,...,...,...,...,...,...
47058,pawelkazimierczyk,0,0,9,It's a very good film..\nIn this movie is a lo...,10,40912,8,May,2018,55
47059,arno_caron,0,1,6,Too much.\nWhen Thor becomes Benny Hill. The s...,10,40913,14,September,2018,24
47060,tobiaschabert,0,0,2,Disney makes this movie ridiculous.\nI mean wh...,10,40914,23,May,2018,102
47061,erl-91188,0,1,6,WATCH MORE TAIKA.\nIf your takeaway from this ...,10,40915,11,July,2018,81
47062,sguerdner,0,1,6,"Hail to the war.\nSo, we've seen this movie wi...",10,40916,18,November,2018,74

## Make an unique ID for each REVIEW

In [12]:
dataset['ReviewID'] = pd.factorize(dataset['Review'])[0] + 1
dataset

,User,Usefulness Vote,Total Votes,User's Rating out of 10,Review,MovieID,user_id,Day,Month,Year,TokenCount,ReviewID
0,Paynebyname,1481,2771,4,"The writers got carried away, the directors ov...",1,1,4,May,2019,1965,1
1,jtindahouse,75,127,4,Time travel is such a lazy way to write storie...,1,2,6,May,2019,361,2
2,arclinecreative,100,170,3,Overrated and full of filler.\nContinuity? 350...,1,3,13,May,2019,147,3
3,RetroRick,99,169,3,"downbeat, overblown & so so long. Cuts all you...",1,4,3,August,2019,995,4
4,ACollegeStudent,27,41,8,Not as good as infinity war but a great movie....,1,5,13,December,2021,81,5
...,...,...,...,...,...,...,...,...,...,...,...,...
47058,pawelkazimierczyk,0,0,9,It's a very good film..\nIn this movie is a lo...,10,40912,8,May,2018,55,47037
47059,arno_caron,0,1,6,Too much.\nWhen Thor becomes Benny Hill. The s...,10,40913,14,September,2018,24,47038
47060,tobiaschabert,0,0,2,Disney makes this movie ridiculous.\nI mean wh...,10,40914,23,May,2018,102,47039
47061,erl-91188,0,1,6,WATCH MORE TAIKA.\nIf your takeaway from this ...,10,40915,11,July,2018,81,47040
47062,sguerdner,0,1,6,"Hail to the war.\nSo, we've seen this movie wi...",10,40916,18,November,2018,74,47041

## Final Dataset

In [18]:
final = dataset[['MovieID','user_id','User', 'Total Votes', "User's Rating out of 10", 'ReviewID', 'Review', 'TokenCount', 'Day', 'Month', 'Year']]
final

,MovieID,user_id,User,Total Votes,User's Rating out of 10,ReviewID,Review,TokenCount,Day,Month,Year
0,1,1,Paynebyname,2771,4,1,"The writers got carried away, the directors ov...",1965,4,May,2019
1,1,2,jtindahouse,127,4,2,Time travel is such a lazy way to write storie...,361,6,May,2019
2,1,3,arclinecreative,170,3,3,Overrated and full of filler.\nContinuity? 350...,147,13,May,2019
3,1,4,RetroRick,169,3,4,"downbeat, overblown & so so long. Cuts all you...",995,3,August,2019
4,1,5,ACollegeStudent,41,8,5,Not as good as infinity war but a great movie....,81,13,December,2021
...,...,...,...,...,...,...,...,...,...,...,...
47058,10,40912,pawelkazimierczyk,0,9,47037,It's a very good film..\nIn this movie is a lo...,55,8,May,2018
47059,10,40913,arno_caron,1,6,47038,Too much.\nWhen Thor becomes Benny Hill. The s...,24,14,September,2018
47060,10,40914,tobiaschabert,0,2,47039,Disney makes this movie ridiculous.\nI mean wh...,102,23,May,2018
47061,10,40915,erl-91188,1,6,47040,WATCH MORE TAIKA.\nIf your takeaway from this ...,81,11,July,2018
47062,10,40916,sguerdner,1,6,47041,"Hail to the war.\nSo, we've seen this movie wi...",74,18,November,2018

In [19]:
final.dropna(inplace=True)
final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47061 entries, 0 to 47062
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   MovieID                  47061 non-null  int64
 1   user_id                  47061 non-null  int64
 2   User                     47061 non-null  object
 3   Total Votes              47061 non-null  int64
 4   User's Rating out of 10  47061 non-null  object
 5   ReviewID                 47061 non-null  int64
 6   Review                   47061 non-null  object
 7   TokenCount               47061 non-null  int64
 8   Day                      47061 non-null  object
 9   Month                    47061 non-null  object
 10  Year                     47061 non-null  object
dtypes: int64(5), object(6)
memory usage: 4.3+ MB

C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\2088823229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final.dropna(inplace=True)

## Replace Errors With Median

In [20]:
final['User\'s Rating out of 10'] = pd.to_numeric(final['User\'s Rating out of 10'], errors='coerce')

temp = final['User\'s Rating out of 10'].median()

final.loc[final['User\'s Rating out of 10'].isna(), 'User\'s Rating out of 10']

C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\3965582138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['User\'s Rating out of 10'] = pd.to_numeric(final['User\'s Rating out of 10'], errors='coerce')

47      NaN
143     NaN
255     NaN
397     NaN
491     NaN
         ..
46904   NaN
46907   NaN
46956   NaN
46983   NaN
47044   NaN
Name: User's Rating out of 10, Length: 1282, dtype: float64

In [22]:
final['User\'s Rating out of 10'].fillna(temp, inplace=True)
final["User's Rating out of 10"].unique()

C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\3266339161.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final['User\'s Rating out of 10'].fillna(temp, inplace=True)
C:\Users\Alireza HR\AppData\Local\Temp\ipykernel_13228\3266339161.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['User\'s Rating out of 10'].fillna(temp, inplace=True)

array([ 4.,  3.,  8.,  1.,  2.,  6.,  9.,  7., 10.,  5.])

In [23]:
final.to_csv('MovieReview.csv', index=False)